### ISSUE TITLE
Some of the subtitles cause some Encoding issues make sure errors are handled properly

### ISSUE THREAD

**Issue by abidulrmdn** [abdrmdn/youtubeSearch#18]
Log from the errors
abidul.rmdn@abiduls-mbp-2 ~/w/y2search> make crawlVideos
docker exec -it y2search_crawler bash -c "go run hello.go"
.
.
.
.
.
.
.
.
.
.
.
.
.
2017/01/07 10:36:15 exit status 1
.
.
.
panic: Error 1366: Incorrect string value: '\xE2\x99\xAA \xE2\x99...' for column 'subtitles' at row 1

goroutine 69 [running]:
panic(0x7b6040, 0xc8204523b0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
main.handleError(0x7fc4d8616f08, 0xc8204564a0)
	/go/src/app/hello.go:32 +0x7e
main.StoreValue(0xc82043b260, 0xb, 0xc82043b270, 0x10, 0xc8200a7180, 0x248, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/app/hello.go:222 +0x750
main.videosHandler(0xc82011c000, 0xc82011c060)
	/go/src/app/hello.go:171 +0x1da
created by main.main
	/go/src/app/hello.go:263 +0xe7
exit status 2
make: *** [crawlVideos] Error 1

**Comment by abidulrmdn** [comment]
It was encoding issues, where video_title or subtitles comes with this kinda content "'\xE2\x99\xAA \xE2\x99" which are kinda smiley faces and so on.
so we changed from utf8 to utf8mb4 which allows 3bytes chars
